/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as ReconciliationsRouteImport } from './routes/reconciliations'
import { Route as PressDemoRouteImport } from './routes/press-demo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReconciliationsIndexRouteImport } from './routes/reconciliations.index'
import { Route as ReconciliationsRunIdRouteImport } from './routes/reconciliations.$runId'

const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconciliationsRoute = ReconciliationsRouteImport.update({
  id: '/reconciliations',
  path: '/reconciliations',
  getParentRoute: () => rootRouteImport,
} as any)
const PressDemoRoute = PressDemoRouteImport.update({
  id: '/press-demo',
  path: '/press-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconciliationsIndexRoute = ReconciliationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReconciliationsRoute,
} as any)
const ReconciliationsRunIdRoute = ReconciliationsRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => ReconciliationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/press-demo': typeof PressDemoRoute
  '/reconciliations': typeof ReconciliationsRouteWithChildren
  '/sources': typeof SourcesRoute
  '/reconciliations/$runId': typeof ReconciliationsRunIdRoute
  '/reconciliations/': typeof ReconciliationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/press-demo': typeof PressDemoRoute
  '/sources': typeof SourcesRoute
  '/reconciliations/$runId': typeof ReconciliationsRunIdRoute
  '/reconciliations': typeof ReconciliationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/press-demo': typeof PressDemoRoute
  '/reconciliations': typeof ReconciliationsRouteWithChildren
  '/sources': typeof SourcesRoute
  '/reconciliations/$runId': typeof ReconciliationsRunIdRoute
  '/reconciliations/': typeof ReconciliationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/press-demo'
    | '/reconciliations'
    | '/sources'
    | '/reconciliations/$runId'
    | '/reconciliations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/press-demo'
    | '/sources'
    | '/reconciliations/$runId'
    | '/reconciliations'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/press-demo'
    | '/reconciliations'
    | '/sources'
    | '/reconciliations/$runId'
    | '/reconciliations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PressDemoRoute: typeof PressDemoRoute
  ReconciliationsRoute: typeof ReconciliationsRouteWithChildren
  SourcesRoute: typeof SourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconciliations': {
      id: '/reconciliations'
      path: '/reconciliations'
      fullPath: '/reconciliations'
      preLoaderRoute: typeof ReconciliationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press-demo': {
      id: '/press-demo'
      path: '/press-demo'
      fullPath: '/press-demo'
      preLoaderRoute: typeof PressDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconciliations/': {
      id: '/reconciliations/'
      path: '/'
      fullPath: '/reconciliations/'
      preLoaderRoute: typeof ReconciliationsIndexRouteImport
      parentRoute: typeof ReconciliationsRoute
    }
    '/reconciliations/$runId': {
      id: '/reconciliations/$runId'
      path: '/$runId'
      fullPath: '/reconciliations/$runId'
      preLoaderRoute: typeof ReconciliationsRunIdRouteImport
      parentRoute: typeof ReconciliationsRoute
    }
  }
}

interface ReconciliationsRouteChildren {
  ReconciliationsRunIdRoute: typeof ReconciliationsRunIdRoute
  ReconciliationsIndexRoute: typeof ReconciliationsIndexRoute
}

const ReconciliationsRouteChildren: ReconciliationsRouteChildren = {
  ReconciliationsRunIdRoute: ReconciliationsRunIdRoute,
  ReconciliationsIndexRoute: ReconciliationsIndexRoute,
}

const ReconciliationsRouteWithChildren = ReconciliationsRoute._addFileChildren(
  ReconciliationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PressDemoRoute: PressDemoRoute,
  ReconciliationsRoute: ReconciliationsRouteWithChildren,
  SourcesRoute: SourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
